### ISSUE TITLE
Acknowledge action for HOST issue does not work 

### ISSUE THREAD

**Issue by ysibirski** [opsgenie/oec-scripts#42] opened 2020-10-09 16:11 UTC
When attempting to acknowledge a ‘host’ alert, actionExecutor.py is not successfully acknowledging the issue on icigna2.  We have identified this as an issue on line 82, where `content_map [“type”]` is being forced to “Service” although it is being successfully set (to either “Service” or “Host”) in “main()“.  Removing line 82 `content_map[“type”] = “Service”` allows the acknowledging to work for both host and service. That issue was successfully debugged with @lumi-pwhitney.

Thank you in advance.

**Comment by peppermor** [comment] 2020-12-11 14:46
I am also facing this issue. one more thing is that when un'ack in opsgenie nothing happens on Icinga side because host was never acked only services

**Comment by lumi-yuri** [comment] 2020-12-11 14:49
@peppermor take a look at this PR. Perhaps, if you can change the script manually it will work for you as expected. This fix did the trick for us: https://github.com/opsgenie/oec-scripts/pull/43

**Comment by lumi-pwhitney** [comment] 2020-12-29 17:07
This appears to have been resolved in https://github.com/opsgenie/oec-scripts/pull/52

**Comment by ahalac-atlassian** [comment] 2022-11-23 13:12
Hi @ysibirski, can you check whether issue is still reproducible? If not, we can close this issue

**Comment by ysibirski** [comment] 2022-11-23 14:08
It looks good now @ahalac-atlassian. Closing this issue.

**Closed** 2022-11-23 14:08 UTC
